LET="POD_NAME=LOCAL
EXECUTOR_ENV_READY=Ready
COLLECTOR_ENV_READY=Ready
WATCHER_SOCK_PATH=/tmp/watcher.sock
COLLECTOR_SOCK_PATH=/tmp/collector.sock
TARGET_INTERFACE_NAME=lo

DRIVER_CONTROL_PORT=9090
DESIRED_EXECUTOR_NUMBER=3"

for en in $LET; do
	export $en
done
