apiVersion: v1
kind: ConfigMap
metadata:
  name: executor-env
data:
  "EXECUTOR_ENV_READY": "Ready"
  "WATCHER_SOCK_PATH": "/socket/watcher.sock"
  "RUNNER_SOCK_PATH": "/socket/runner.sock"
  "COLLECTOR_SOCK_PATH": "/socket/collector.sock"
  "TARGET_INTERFACE_NAME": "eth0"
---
apiVersion: v1
kind: Pod
metadata:
  name: executor
  labels:
    app: data-executor
spec:
  volumes:
  - name: socket-dir
    emptyDir: {}
  containers:
  - name: runner
    image: golang:1.24.1-bullseye
    command: ["sh", "-c", "sleep infinity"]
    volumeMounts:
    - name: socket-dir
      mountPath: /socket
    envFrom:
    - configMapRef:
        name: executor-env
  - name: watcher
    image: golang:1.24.1-bullseye
    command: ["sh", "-c", "sleep infinity"]
    volumeMounts:
    - name: socket-dir
      mountPath: /socket
    securityContext:
      privileged: true
      capabilities:
        add: ["NET_ADMIN", "SYS_ADMIN"]
    env:
    - name: NODE_NAME
      valueFrom:
        fieldRef:
          fieldPath: spec.nodeName
    envFrom:
    - configMapRef:
        name: executor-env




