apiVersion: v1
kind: ConfigMap
metadata:
  name: executor-env
data:
  "EXECUTOR_ENV_READY": "Ready"
  "DRIVER_CONTACT_PROTO": "tcp"
  "DRIVER_CONTACT_FQDN": "driver-svc.default.svc.cluster.local:8080"
  "WATCHER_SOCK_TYPE": "unix"
  "WATCHER_SOCK_PATH": "/socket/watcher.sock"
  "RUNNER_SOCK_PATH": "/socket/runner.sock"
  "RUNNER_REQUEST_RECEIVE_PROTO": "tcp"
  "RUNNER_REQUEST_RECEIVE_PORT": ":8080"
  "COLLECTOR_SOCK_PATH": "/socket/collector.sock"
  "TARGET_INTERFACE_NAME": "eth0"
---
# Deploy로 수정해야할 듯?
apiVersion: v1
kind: Pod
metadata:
  name: executor
  labels:
    app: executor
spec:
  volumes:
  - name: socket-dir
    emptyDir: {}
  - name: collector-socket
    hostPath:
      type: Socket
      path: /var/run/ebpf-sidecar-poc/collector.sock
  containers:
  - name: runner
    image: tori209/ebpf-sidecar-poc:0.5
    imagePullPolicy: "Always"
    #command: ["sh", "-c", "sleep infinity"]
    command: ["./runner"]
    workingDir: "/go/src/executor/bin"
    volumeMounts:
    - name: socket-dir
      mountPath: /socket
    envFrom:
    - configMapRef:
        name: executor-env
  - name: watcher
    image: tori209/ebpf-sidecar-poc:0.5
    imagePullPolicy: "Always"
    command: ["./watcher"]
    workingDir: "/go/src/executor/bin"
    volumeMounts:
    - name: socket-dir
      mountPath: /socket
    - name: collector-socket
      mountPath: /socket/collector.sock
    securityContext:
      privileged: true
      capabilities:
        add: ["NET_ADMIN", "SYS_ADMIN"]
    env:
    - name: NODE_NAME
      valueFrom:
        fieldRef:
          fieldPath: spec.nodeName
    - name: POD_NAME
      valueFrom:
        fieldRef:
          fieldPath: metadata.name
    envFrom:
    - configMapRef:
        name: executor-env
  imagePullSecrets:
  - name: regcred




