apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: collector-ds
  labels:
    app: go-collector
    purpose: ds-log-collector
spec:
  selector:
    matchLabels:
      app: go-collector-pod
      purpose: ds-log-collector
  template:
    metadata:
      labels:
        app: go-collector-pod
        purpose: ds-log-collector
    spec:
      volumes:
      - name: socket-dir
        hostPath:
          type: DirectoryOrCreate
          path: /var/run/ebpf-sidecar-poc
      containers:
      - name: collector
        image: tori209/ebpf-sidecar-poc:${TAG_NAME}
        imagePullPolicy: "Always"
        command: ["bin/collector"]
        workingDir: "/go/src/executor"
        volumeMounts:
        - name: socket-dir
          mountPath: /socket
        env:
        - name: SECRET_COLLECTOR_TOKEN
          valueFrom:
            secretKeyRef:
              name: collector-influxdb-token
              key: collector-token
        envFrom:
        - configMapRef:
            name: collector-env
      imagePullSecrets:
      - name: regcred

