apiVersion: v1
kind: ConfigMap
metadata:
  name: collector-env
data:
  "COLLECTOR_ENV_READY": "Ready"
  "COLLECTOR_SOCK_PATH": "/socket/collector.sock"
  "COLLECTOR_ORG": "${COLLECTOR_INFLUXDB_ORG}"
  "COLLECTOR_BUCKET": "${COLLECTOR_INFLUXDB_BUCKET}"
  "INFLUXDB_URL": "${INFLUXDB_URL}"
  "POSTGRES_TASKDB_DSN": "postgres://postgres:${POSTGRES_ADMIN_PASSWORD}@${POSTGRES_URL}/${POSTGRES_DB}?sslmode=disable"

