apiVersion: v1
kind: ConfigMap
metadata:
  name: driver-env
data:
  "DRIVER_ENV_READY": "Ready"
  "DESIRED_EXECUTOR_NUMBER": "${EXECUTOR_CNT}"
  "RUNNER_REQUEST_RECEIVE_PROTO": "tcp"
  "RUNNER_REQUEST_RECEIVE_PORT": ":8080"
  "POSTGRES_TASKDB_DSN": "postgres://postgres:${POSTGRES_ADMIN_PASSWORD}@${POSTGRES_URL}/${POSTGRES_DB}?sslmode=disable"
  "NORMAL_MINIO_ENDPOINT": "${NORMAL_MINIO_ENDPOINT}"
  "NORMAL_MINIO_BUCKET": "${NORMAL_MINIO_BUCKET}"
  "MALICIOUS_MINIO_ENDPOINT": "${MALICIOUS_MINIO_ENDPOINT}"
  "MALICIOUS_MINIO_BUCKET": "${MALICIOUS_MINIO_BUCKET}"
  "DATA_BEGIN": "0"
  "DATA_END": "10000"
  "MAKE_ANOMALY": "${MAKE_ANOMALY}"

