apiVersion: v1
kind: Pod
metadata:
  name: driver
  labels:
    app: driver
spec:
  containers:
  - name: manager
    image: tori209/ebpf-sidecar-poc:${TAG_NAME}
    imagePullPolicy: "Always"
    command: ["./driver"]
    workingDir: "/go/src/executor/bin"
    ports:
    - containerPort: 8080
      name: driver-port
    envFrom:
    - configMapRef:
        name: driver-env
  imagePullSecrets:
  - name: regcred
---
apiVersion: v1
kind: Service
metadata:
  name: driver-svc
  labels:
    app: driver-svc
spec:
  selector:
    app: driver
  ports:
  - name: driver-svc-port
    protocol: TCP
    port: 8080
    targetPort: driver-port

