# Deploy로 수정해야할 듯?
apiVersion: apps/v1
kind: Deployment
metadata:
  name: executor
spec:
  replicas: ${EXECUTOR_CNT}
  selector:
    matchLabels: &pod_labels
      app: executor
      purpose: ebpf-sidecar-poc
  template:
    metadata:
      name: executor
      labels:
        <<: *pod_labels
    spec:
      volumes:
      - name: socket-dir
        emptyDir: {}
      - name: collector-socket
        hostPath:
          type: Socket
          path: /var/run/ebpf-sidecar-poc/collector.sock
      containers:
      - name: runner
        image: tori209/ebpf-sidecar-poc:${TAG_NAME}
        imagePullPolicy: "Always"
        command: ["./runner"]
        workingDir: "/go/src/executor/bin"
        ports:
        - containerPort: 8080
          name: runner-port
        volumeMounts:
        - name: socket-dir
          mountPath: /socket
        envFrom:
        - configMapRef:
            name: executor-env
      - name: watcher
        image: tori209/ebpf-sidecar-poc:${TAG_NAME}
        imagePullPolicy: "Always"
        command: ["./watcher"]
        workingDir: "/go/src/executor/bin"
        volumeMounts:
        - name: socket-dir
          mountPath: /socket
        - name: collector-socket
          mountPath: /socket/collector.sock
        securityContext:
          privileged: false
          capabilities:
            add: ["NET_ADMIN", "BPF", "PERFMON"]
        env:
        - name: NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        envFrom:
        - configMapRef:
            name: executor-env
      imagePullSecrets:
      - name: regcred

