apiVersion: v1
kind: ConfigMap
metadata:
  name: executor-env
data:
  "EXECUTOR_ENV_READY": "Ready"
  "DRIVER_CONTACT_PROTO": "tcp"
  "DRIVER_CONTACT_FQDN": "driver-svc.${NAMESPACE}.svc.cluster.local:8080"
  "WATCHER_SOCK_TYPE": "unix"
  "WATCHER_SOCK_PATH": "/socket/watcher.sock"
  "RUNNER_SOCK_PATH": "/socket/runner.sock"
  "RUNNER_REQUEST_RECEIVE_PROTO": "tcp"
  "RUNNER_REQUEST_RECEIVE_PORT": ":8080"
  "RUNNER_MODE_IS_SIMPLE": "${RUNNER_MODE_IS_SIMPLE}"
  "COLLECTOR_SOCK_PATH": "/socket/collector.sock"
  "TARGET_INTERFACE_NAME": "eth0"
  "NORMAL_MINIO_ENDPOINT": "${NORMAL_MINIO_ENDPOINT}"
  "NORMAL_MINIO_BUCKET": "${NORMAL_MINIO_BUCKET}"
  "MALICIOUS_MINIO_ENDPOINT": "${MALICIOUS_MINIO_ENDPOINT}"
  "MALICIOUS_MINIO_BUCKET": "${MALICIOUS_MINIO_BUCKET}"
  "MINIO_COMMON_ID": "${MINIO_COMMON_ID}"
  "MINIO_COMMON_PW": "${MINIO_COMMON_PW}"


